name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      name: Check out code

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version

    - name: Debug Environment
      run: |
        java -version
        mvn -version
        ls -la ${{ github.workspace }}
        which google-chrome

    - name: Build and Test with Maven
      run: mvn -B test --file pom.xml

    - name: Package with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Debug Artifact Path
      if: failure()
      run: ls -la target/surefire-reports/ || echo "Directory not found"

    - name: Upload Test Reports (if failed)
      if: failure()
      uses: actions/upload-artifact@v3.1.2  # Pin to a specific version
      with:
        name: surefire-reports
        path: target/surefire-reports/